import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Flex, Arimo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AnnouncementBanner from "@/components/AnnouncementBanner";
import HeroSection from "@/components/HeroSection";
import BurgerMenu from "@/components/BurgerMenu";
import CategorySection from "@/components/CategorySection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoFlex = Roboto_Flex({
  variable: "--font-roboto-flex",
  subsets: ["latin"],
});

const arimo = Arimo({
  variable: "--font-arimo",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoFlex.variable} ${arimo.variable} antialiased`}
      >
        <BurgerMenu />
        <AnnouncementBanner
          messages={[
            "Free shipping over ₹499 | Additional 15% discount on purchases above ₹1000",
            "Limited time offer: Buy 2 Get 1 Free on selected items",
            "New arrivals: Explore our latest home collection"
          ]}
         />
        <Navbar />
        <HeroSection />
        <CategorySection />
        <div className="pt-20">
          {children}
        </div>
      </body>
    </html>
  );
}
